FROM node:18.12.1-alpine

WORKDIR /usr/app

ARG FIREBASE_API_KEY
ARG FIREBASE_MESSAGING_SENDER_ID
ARG FIREBASE_APP_ID

ENV NEXT_PUBLIC_FIREBASE_API_KEY=${FIREBASE_API_KEY}
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_API_KEY}
ENV NEXT_PUBLIC_FIREBASE_APP_ID=${FIREBASE_API_KEY}
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=aicte-diary.firebaseapp.com
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=aicte-diary
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=aicte-diary.appspot.com


COPY . .

RUN yarn install --frozen-lockfile

RUN yarn build 

CMD ["yarn", "start"]
